spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  liquibase:
    drop-first: true

application:
  locale: ru-RU